### ISSUE TITLE
Feature Request: Integration between Simply Jetpacks and Redstone Armory

### ISSUE THREAD

**Issue by AlexPlus117** [Tonius/SimplyJetpacks#109]
Hi Tonius, I'd like to see some integration between your Simply Jetpacks mod and Redstone Armory. Is this possible to do? Thanks in advance...

**Comment by nabijaczleweli** [comment]
What kind of interaction?
Your issue is worthless right now.

**Comment by AlexPlus117** [comment]
It isn't an issue, it's just a request of integration between the two mods I mentioned.

**Comment by nabijaczleweli** [comment]
"@AlexPlus117 opened this Issue 23 hours ago"


Anyway, what kind of integration?

**Comment by AlexPlus117** [comment]
You know that Simply Jetpacks mod adds Flux-Infused JetPlate, a strengthening of Redstone Arsenal Flux-Infused Chestplate. Well, I'd like to see added also a strengthening of Redstone Armory Enderium Flux Chestplate, like an Enderium Flux JetPlate. It might be a good idea...

**Comment by MyDeloreanWontStart** [comment]
I think it has an enderium flux skin now, for a few versions

**Comment by AlexPlus117** [comment]
Yes, but it has the same strength of the Flux-Infused JetPlate (50M RF) and it can be crafted without Redstone Armory. I'd like a real strengthening of the Enderium Flux Chestplate.

**Comment by Badcholo** [comment]
Why do you need it to be any better than what it already is? It's awesome the way it is, i consider it lucky that they made a skin for it so that it would match. There really isn't much difference between RA and SJ. It's why i never used RA, It's like wasting materials for minuscule, barely noticeable difference.

**Comment by Razorskills** [comment]
Well really,  instead of making support for another mod,  that really is suposed to be an example mod. Should really just make another mod called Simply Armour. Full armor sets that match each tier of simply jet packs. And follow the same tier levels. The only reason I use RA,  is for the other peices of armor. I would much rather not even use RA.

**Comment by Badcholo** [comment]
http://www.technicpack.net/modpack/mojangsters.583708
Mojangsters Modpack. I just went with Power Armor.
QMX made a fixed up version for 1.7.10
.jar are in my modpack.

**Comment by Tonius** [comment]
The Enderium Flux Overlay exists to make the Flux-Infused JetPlate fit better when wearing the Enderium Flux set. I'd rather not make the JetPlate even more powerful than it already is.
