### ISSUE TITLE
Putting a Jetpack from this mod into the Filler from RotaryCraft crashes the game.

### ISSUE THREAD

**Issue by C1ffisme** [Tonius/SimplyJetpacks#125]
I put a jetpack from this mod into the jetpack filler from RotaryCraft. This froze Minecraft for a few seconds, and then crashed. After that I could not enter the world again, and I had to delete it.

I couldn't seem to post this bug on the RotaryCraft page, it didn't seem to be able to support issues, only pull requests. So I posted it here for people to notice.

**Comment by nabijaczleweli** [comment]
Please post the crash log when reporting crashes, so developers can actually look into what causes it.

**Comment by C1ffisme** [comment]
I don't think I had a crash report, it was from the FTB launcher, but I'll try again soon if I'm reminded.

**Comment by flaviocysne** [comment]
I put a Dark Soularium JetPlate in a MrCrayfish's Washing Machine and the texture got all mixed up. It did show all textures of jetplates' prior versions and then crashed the game. I was able to load the game after this, but after breaking the MrCrayfish's Washing Machine the original item was messed up and had its texture gone (purple-black cube). Then, when I tried to get the item, the game crashed again and I was not able to load it since.

I'll add the game crash report as soon as I can.

Minecraft version: 1.7.10 (not tested in earlier versions)
Modpack version: Project Ozone 2 Reloaded 2.3.0

**Comment by C1ffisme** [comment]
If I remember correctly I was using a 1.6.4 pack when the game crashed. (FTB Tech 2 I think...) I imagine that this mod has progressed quite a bit since that version, so I think I'll close this issue. (Plus a quick glance tells me that this mod hasn't gotten updates in two years.)

@flaviocysne What you're describing seems to be a different issue, and I'd suggest starting another issue. (It doesn't even sound like it's related to this mod... Unless Dark Soularium Jetplanes are from this mod.)
