### ISSUE TITLE
Jetpack sounds

### ISSUE THREAD

**Issue by Tonius** [Tonius/SimplyJetpacks#26]
Jetpacks could use some kind of subtle sound effect when people are flying with it.

**Comment by Tonius** [comment]
I have looked at your work, and here is my feedback.

It's a good start, but having a sound 'pulse' every few ticks sounds a bit weird IMO. I think it would sound much nicer with a single, longer sound that loops. As far as I know, MC's sound system can handle loops... somehow (TE and Mekanism make use of that). What do you think?

As for the sound itself, I'd imagine a jetpack sounds a bit more like a gentle jet engine, if you know what I mean. The gas burner sound is close, though. (It's hard to describe sounds...)

**Comment by nabijaczleweli** [comment]
Thank you for your feedback.
I started working on it about half an hour ago and it looks like it is possible.
Sound itself can be anything you want, really. I used the gas burner because it sounded OK.

**Comment by nabijaczleweli** [comment]
I have the code for it now, turns out I was an idiot and didn't search through all of the call tree, because I would find this solution if I did. The solution is:
* `Jetpack` sends a packet to play "jetpack_flight_idle".
* We catch the event and cancel it.
* We play our own `ISound` subclass (`MovingSoundIdleJetpack`) that repositions itself every tick and stops if `user` is not actively flying or the sound ends.

The changing of sound is really simple now: download it, convert to 'ogg', replace "jetpack_flight_idle.ogg" in "assets/simplyjetpacks/sounds", and change
```java
private int left = 126;
```
in `MovingSoundIdleJetpack` (line 23 ATM) with `([sound length in seconds] / (1 / 20))`.

**Comment by nabijaczleweli** [comment]
I've [pushed a commit](https://github.com/nabijaczleweli/SimplyJetpacks/commit/a33066af9683c80c4a5bc45cf4a8237ac80e52fc) to my fork, and would really appreciate any sort of feedback (like "It's absolutely horrible, get out" or "It's OK", or something along those lines), if You don't mind.

**Comment by Tonius** [comment]
Very nice. I have now also done some tweaks myself. Most importantly, I moved all the logic to the client side. If you'd like to do some work still, you can merge this new branch into your fork:
https://github.com/Tonius/SimplyJetpacks/commits/sounds

I you think it's fine how it is, just tell me and I'll take care of the rest and will credit you appropriately.

**Comment by nabijaczleweli** [comment]
If it works for you, great!
I do think code is fine how it is, but you might want to change the idle flying sound to something more appropriate/better.
I think it's all from me for now.
